### ISSUE TITLE
Add "Tutorengrillen" date

### ISSUE THREAD

**Issue by Feliix42** [fsr/esetutorenleitfaden#3]
After lots of tutors missed the "Tutorengrillen" this year, it would might help if we put the date in this book to make it more "present" and harder to miss it.

(Obviously an improvement for the next year)

**Comment by Amyy** [comment]
is still an issue in 2019 version because date for "Tutorengrillen" is unknown yet :D

**Comment by niklaskeerl** [comment]
Tutorengrillen will be on Saturday, October 5th
